### ISSUE TITLE
Initial gcc compile fails under linux

### ISSUE THREAD

**Issue by pneumaticdeath** [Helco/PLocalSim#35]
Environment: Ubuntu12.04, SDK 2.0BETA7
When I try to run build.local.sh, I get the following output:
mitch@phobos:~/pebble-dev/workspace/berlin_clock$ build.local.sh 
In file included from /usr/include/stdint.h:26:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/4.6/include/stdint.h:3,
                 from ./build/tempLocal/src/resource_ids.auto.h:7,
                 from /home/mitch/pebble-dev/PebbleSDK-2.0-BETA7/bin/../Pebble/include/pebble.h:4,
                 from ./src/berlin_clock.c:1:
/usr/include/features.h:324:26: fatal error: bits/predefs.h: No such file or directory
compilation terminated.

Is this because I'm running on 2.0 SDK?  It seems like it's deep inside standard header includes (stdint.h)

The code can be found here: https://github.com/pneumaticdeath/berlin_clock

**Comment by mariettiell** [comment]
Same Problem
